-- 코드를 입력하세요
SELECT B.BOOK_ID AS BOOK_ID
    , A.AUTHOR_NAME AS AUTHOR_NAME
    , DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B
JOIN AUTHOR A
ON (B.AUTHOR_ID = A.AUTHOR_ID AND B.CATEGORY= '경제') -- 경제에 해당하는 데이터만 조인 처리하는게 더 나을듯!
GROUP BY CATEGORY, BOOK_ID
ORDER BY PUBLISHED_DATE
;